version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception_net
    expose:
      - "3306"
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception_net
volumes:
  wordpress_db:

networks:
  inception_net:
