version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_db:/var/lib/mysql
    networks:
      - inception_net
    expose:
      - "3306"
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443" # "host(VM):container"
    networks:
      - inception_net
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    expose:
      - "9000"
volumes:
  mariadb_db:
  wordpress:

networks:
  inception_net:
