version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception_net
    expose:
      - "3306"
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - wordpressfiles_vol:/var/www/html
    ports:
      - "443:443" # "host(VM):container"
    networks:
      - inception_net
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpressfiles_vol:/var/www/html
    networks:
      - inception_net
    expose:
      - "9000"

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/mgimon-c/data/mariadb
      o: bind

  wordpressfiles_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/mgimon-c/data/wordpress
      o: bind

networks:
  inception_net:
